import { GetServerSideProps, InferGetServerSidePropsType } from 'next'
import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'
import { atom, useAtom } from 'jotai'
import { useAtomValue, useHydrateAtoms } from 'jotai/utils'

const countAtom = atom(0)
const doubleAtom = atom((get) => get(countAtom) * 2)

export const getServerSideProps: GetServerSideProps<{
  initialCount: number
}> = async (context) => {
  return { props: { initialCount: 42 } }
}

export default function Home({ initialCount }: InferGetServerSidePropsType<typeof getServerSideProps>) {
  useHydrateAtoms([[countAtom, initialCount]] as const)
  const [count, setCount] = useAtom(countAtom)
  const doubleCount = useAtomValue(doubleAtom)
  return (
    <div className={styles.container}>
      <Head>
        <title>with-jotai</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <h1 className={styles.title}>Main Page</h1>
      <h1 className="text-3xl font-bold underline">TailWind Test</h1>
      <main className={styles.main}>
        <div className="p-6 max-w-sm mx-auto bg-white rounded-xl shadow-lg flex items-center space-x-4">
          <div className="shrink-0">
            <img className="h-12 w-12" src="/fake-logo.png" alt="ChitChat Logo" />
          </div>
          <div>
            <div className="text-xl font-medium text-black">Tailwind Test</div>
            <p className="text-slate-500">You have a new message!</p>
          </div>
        </div>
        <div>Initial count from the server: {count}</div>
        <div>Double count: {doubleCount}</div>
        <button onClick={() => setCount((count) => count + 1)}>+1</button>
      </main>
      <footer className={styles.footer}>
        <a
          href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
          target="_blank"
          rel="noopener noreferrer">
          Powered by DND 6-10
        </a>
      </footer>
    </div>
  )
}
