/* 유저 관련 */
export const USER_PROFILE_KEY = 'USER_PROFILE_KEY'
export const USE_FOLLOWERS_KEY = 'USE_FOLLOWERS_KEY'
export const USE_FOLLOWINGS_KEY = 'USE_FOLLOWINGS_KEY'

/* 글귀 관련 */
export const USE_POST_KEY = 'USE_POST_KEY'
export const USE_MY_POSTS_KEY = 'USE_MY_POSTS_KEY'
export const USE_USER_POSTS_KEY = 'USE_USER_POSTS_KEY'
export const USE_INFINITE_POSTS_KEY = 'USE_INFINITE_POSTS_KEY'
export const USE_INFINITE_MAIN_POSTS_KEY = 'USE_INFINITE_MAIN_POSTS_KEY'
export const USE_MY_LIKED_POSTS_KEY = 'USE_MY_LIKED_POSTS_KEY'

/* 토픽 관련 */
export const USE_MAIN_TOPICS_KEY = 'USE_MAIN_TOPICS_KEY'
export const USE_POST_TOPICS_KEY = 'USE_POST_TOPICS_KEY'
export const USE_SEARCH_TOPICS_KEY = 'USE_SEARCH_TOPICS_KEY'

/* 댓글 관련 */
export const USE_POST_REPLIES_KEY = 'USE_POST_REPLIES_KEY'
